# -*- coding: utf-8 -*-
"""EDA_Task1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wWethfIX5pITRxq0Xh6D-e0iqKMWvqkX

## **Task 1:**

## Exploratory Data Analysis For Restaurant dataset.
"""

import pandas as pd

# Load the dataset
file_path = 'dataset.csv'
data = pd.read_csv(file_path)

# Display basic information about the dataset
data_info = data.info()
data_head = data.head()

data_info, data_head

"""#1 . **Summary Statistics**"""

# Summary statistics for numerical columns
summary_stats = data.describe()

# Distribution of categorical columns
categorical_columns = data.select_dtypes(include=['object']).columns
categorical_distribution = data[categorical_columns].describe()

summary_stats, categorical_distribution

"""# 2 .Missing Values Analysis"""

# Count of missing values in each column
missing_values = data.isnull().sum()

missing_values

"""# 3 .Correlation Analysis"""

# Correlation matrix for numerical columns
# Select only numerical columns before calculating correlations
numerical_data = data.select_dtypes(include=['number'])
correlation_matrix = numerical_data.corr()

correlation_matrix

"""# 4. Visualization"""

import matplotlib.pyplot as plt

# Plot histograms for numerical columns
numerical_columns = data.select_dtypes(include=['float64', 'int64']).columns

data[numerical_columns].hist(bins=15, figsize=(15, 10))
plt.suptitle('Histograms of Numerical Columns')
plt.show()

"""### **4.1 Box Plots to Understand Distribution and Outliers**"""

# Plot box plots for numerical columns
for column in numerical_columns:
    plt.figure(figsize=(10, 5))
    data.boxplot(column)
    plt.title(f'Box plot of {column}')
    plt.ylabel(column)
    plt.show()